[package]
name = "glass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
iced_gui = ["iced_wgpu", "iced_winit", "iced_native", "iced_graphics"]
egui_gui = ["egui-wgpu", "egui-winit", "egui"]

[dependencies]
indexmap = "1.9.2"
pollster = "0.2.5"
wgpu = "0.14"
winit = "0.27"
image = "0.24"
anyhow = "1.0.68"

# Optional Iced
iced_wgpu = { version = "0.8.0", optional = true }
iced_graphics = { version = "0.6.0", optional = true }
iced_native = { version = "0.8.0", optional = true }
iced_winit = { version = "0.7.0", optional = true }

# Optional Egui
egui-wgpu = { version = "0.20.0", optional = true }
egui-winit = { version = "0.20.1", optional = true }
egui = { version = "0.20.1", optional = true }

[dev-dependencies]
glam = "0.22.0"
bytemuck = { version = "1.12.3", features = ["derive"] }


egui_demo_lib = "0.20.0"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[package.metadata.example.hello_world]
name = "Hello World"
description = "A traditional hello world example"

[[example]]
name = "game_of_life"
path = "examples/game_of_life/main.rs"

[package.metadata.example.game_of_life]
name = "Game Of Life Compute Shader"
description = "Game of life running a compute shader"

[[example]]
name = "multiple_windows"
path = "examples/multiple_windows/main.rs"

[package.metadata.example.multiple_windows]
name = "Multiple Windows"
description = "Example that opens multiple windows on space key"

[[example]]
name = "quad"
path = "examples/quad/main.rs"

[package.metadata.example.quad]
name = "Quad"
description = "Example that renders a basic Quad"

[[example]]
name = "triangle"
path = "examples/triangle/main.rs"

[package.metadata.example.triangle]
name = "Triangle"
description = "Example that renders a basic Triangle"

[[example]]
name = "egui_gui"
path = "examples/egui_gui.rs"
required-features = ["egui_gui"]

[package.metadata.example.egui_gui]
name = "Egui Gui"
description = "Example that runs an egui demo app"

[[example]]
name = "iced_gui"
path = "examples/iced_gui.rs"
required-features = ["iced_gui"]

[package.metadata.example.iced_gui]
name = "Iced Gui"
description = "Example that runs a iced gui with an example button"